version: "3.8"
services:
  backend:
    build: ./backend-api
    ports:
      - "5000:5000"
    environment:
     - DB_HOST=database
     - POSTGRES_USER=myuser
     - POSTGRES_PASSWORD=mypassword
     - POSTGRES_DB=mydatabase
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
     - db-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend   
volumes:
   db-data: 
           
